import os
import requests
from dotenv import load_dotenv
from macro_engine import MacroCompass

load_dotenv()

BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

class TelegramNotifier:
    def __init__(self):
        self.base_url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"

    def send_message(self, text: str) -> bool:
        """Sends an HTML-formatted message to your Telegram."""
        if not BOT_TOKEN or not CHAT_ID:
            print("[Error]: Missing Telegram credentials in .env")
            return False

        payload = {
            "chat_id": CHAT_ID,
            "text": text,
            "parse_mode": "HTML",
            "disable_web_page_preview": True
        }

        try:
            res = requests.post(self.base_url, json=payload, timeout=10)
            data = res.json()
            if data.get("ok"):
                return True
            else:
                print(f"[Telegram API Error]: {data}")
                return False
        except Exception as e:
            print(f"[Network Error sending Telegram]: {e}")
            return False

    def send_macro_briefing(self, report: dict):
        """Formats and pushes the Macro Compass Report."""
        score = report["macro_score"]
        
        # Pick emoji based on score
        if score >= 3:
            badge = "🟢 <b>STRONG BULLISH</b>"
        elif score > 0:
            badge = "🟩 <b>MILD BULLISH</b>"
        elif score == 0:
            badge = "⚪ <b>NEUTRAL / CASH</b>"
        elif score >= -2:
            badge = "🟧 <b>MILD BEARISH</b>"
        else:
            badge = "🔴 <b>STRONG BEARISH</b>"

        message = (
            f"🏛️ <b>XAUUSD MACRO INTEL REPORT</b>\n"
            f"━━━━━━━━━━━━━━━━━━━━\n"
            f"🧭 <b>Bias:</b> {badge} (Score: <b>{score}/5</b>)\n"
            f"🎯 <b>Action:</b> <code>{report['trading_directive']}</code>\n\n"
            f"📊 <b>Intermarket Drivers:</b>\n"
            f"• <b>DXY (USD Index):</b> {report['dxy']['price']} | <i>{report['dxy']['trend']}</i>\n"
            f"• <b>US10Y Yield:</b> {report['us10y']['yield']}% | <i>{report['us10y']['trend']}</i>\n"
            f"• <b>10Y Real TIPS:</b> {report['real_yield_tips']['rate']}% | <i>{report['real_yield_tips']['trend']}</i>\n"
            f"━━━━━━━━━━━━━━━━━━━━\n"
            f"⚡ <i>Generated by XAUUSD Advisory Engine</i>"
        )

        return self.send_message(message)

    def send_trade_alert(self, setup: dict, macro_report: dict) -> bool:
        """Sends an actionable SMC + Macro trade blueprint to Telegram."""
        direction_emoji = "🟢 <b>BUY LIMIT</b>" if setup["direction"] == "BULLISH" else "🔴 <b>SELL LIMIT</b>"
        
        message = (
            f"🚨 <b>NEW XAUUSD INTRADAY TRADE SIGNAL</b>\n"
            f"━━━━━━━━━━━━━━━━━━━━\n"
            f"📋 <b>Order:</b> {direction_emoji}\n"
            f"🧭 <b>Macro Alignment:</b> <code>{macro_report['macro_bias']} ({macro_report['macro_score']}/5)</code>\n"
            f"💡 <b>Logic:</b> <i>{setup['reason']}</i>\n\n"
            f"🎯 <b>EXECUTION BLUEPRINT (MT5):</b>\n"
            f"• <b>Entry Zone:</b> <code>{setup['entry_zone']}</code>\n"
            f"• <b>Stop Loss:</b> <code>${setup['stop_loss']}</code>\n"
            f"• <b>Take Profit 1:</b> <code>${setup['tp1']}</code> (1:2 R:R)\n"
            f"• <b>Take Profit 2:</b> <code>${setup['tp2']}</code> (Opposing Liquidity)\n"
            f"• <b>Estimated R:R:</b> <b>{setup['risk_reward']}</b>\n"
            f"━━━━━━━━━━━━━━━━━━━━\n"
            f"⚠️ <i>Action: Set limit order on MT5. Move SL to Breakeven at TP1.</i>"
        )
        return self.send_message(message)        

if __name__ == "__main__":
    print("\n--- Pulling Macro Intelligence and Pinging Telegram ---")
    compass = MacroCompass()
    report = compass.calculate_macro_bias()

    notifier = TelegramNotifier()
    success = notifier.send_macro_briefing(report)

    if success:
        print("✅ Success! Check your Telegram on your phone.")
    else:
        print("❌ Failed to send. Double-check your TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID in .env")